import fs from 'fs';
const lines = fs.readFileSync('src/pages/ShopPage.jsx', 'utf8').split('\n');
const target = '<span className="absolute -top-2 -right-2 bg-[#7C3AED] text-white text-[10px] font-bold w-5 h-5 flex items-center justify-center rounded-full border-2 border-[#1A1F2F]">';
const idx = lines.findIndex(l => l.includes(target));

if (idx >= 0) {
    const newLines = lines.slice(0, idx + 1).concat([
'                            {invItem.quantity}',
'                          </span>',
'                        </div>',
'                        <div>',
'                          <h3 className="font-bold text-sm text-[#DEE1F7]">{name}</h3>',
'                        </div>',
'                      </div>',
'                      <button onClick={() => handleConsume(id)} className="px-4 py-2 bg-[#7C3AED] text-white font-bold text-xs rounded-xl shadow-[0_0_15px_rgba(124,58,237,0.4)] hover:bg-[#6D28D9] transition-transform hover:scale-105 uppercase tracking-wider">',
'                        Usa',
'                      </button>',
'                    </div>',
'                  );',
'                })',
'              )}',
'            </motion.div>',
'          )}',
'        </AnimatePresence>',
'      </motion.div>',
'',
'      {/* Healing Effect */}',
'      <HealingEffect show={showHealing} onComplete={() => setShowHealing(false)} />',
'',
'      {/* Task Selector Modal per Pergamena del Tempo */}',
'      <AnimatePresence>',
'        {showTaskSelector && (',
'          <motion.div',
'            initial={{ opacity: 0 }}',
'            animate={{ opacity: 1 }}',
'            exit={{ opacity: 0 }}',
'            className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"',
'          >',
'            <motion.div',
'              initial={{ scale: 0.9, opacity: 0, y: 20 }}',
'              animate={{ scale: 1, opacity: 1, y: 0 }}',
'              exit={{ scale: 0.9, opacity: 0, y: -20 }}',
'              className="glass-card w-full max-w-sm p-6 rounded-3xl border border-[rgba(245,158,11,0.3)] shadow-[0_4px_32px_rgba(245,158,11,0.2)] relative"',
'            >',
'               <div className="flex items-center gap-3 mb-4">',
'                 <span className="text-3xl">📜</span>',
'                 <div>',
'                   <h3 className="font-bold text-lg text-[#FCD34D]">Usa Pergamena</h3>',
'                   <p className="text-xs text-[#958DA1]">Seleziona il task da spostare a domani.</p>',
'                 </div>',
'               </div>',
'               ',
'               <div className="max-h-60 overflow-y-auto space-y-2 mb-4 custom-scrollbar">',
'                 {tasks.filter(t => !t.completed && t.type !== \'habit\').length === 0 ? (',
'                    <p className="text-sm text-[#958DA1] text-center py-4">Nessun task disponibile.</p>',
'                 ) : (',
'                   tasks.filter(t => !t.completed && t.type !== \'habit\').map(task => (',
'                     <button',
'                       key={task.id}',
'                       onClick={async () => {',
'                         const tomorrow = new Date();',
'                         tomorrow.setDate(tomorrow.getDate() + 1);',
'                         const dl = tomorrow.toISOString().split(\'T\')[0];',
'                         await updateTask(task.id, { deadline: dl });',
'                         await consumeItem(user.uid, \'resurrect_scroll\', false);',
'                         setShowTaskSelector(false);',
'                       }}',
'                       className="w-full text-left p-3 rounded-xl bg-white/5 border border-white/10 hover:bg-white/10 transition-colors flex justify-between items-center"',
'                     >',
'                       <span className="text-sm font-medium text-white truncate pr-2">{task.title}</span>',
'                       {task.deadline && <span className="text-[10px] text-[#958DA1] shrink-0">{task.deadline}</span>}',
'                     </button>',
'                   ))',
'                 )}',
'               </div>',
'               ',
'               <button',
'                 onClick={() => setShowTaskSelector(false)}',
'                 className="w-full py-3 bg-white/5 hover:bg-white/10 text-white rounded-xl font-bold text-sm transition-colors"',
'               >',
'                 Annulla',
'               </button>',
'            </motion.div>',
'          </motion.div>',
'        )}',
'      </AnimatePresence>',
'',
'    </div>',
'  );',
'}']);
    fs.writeFileSync('src/pages/ShopPage.jsx', newLines.join('\n'), 'utf8');
    console.log('Fixed');
} else {
    console.log('Not found');
}
